// global constants
global.BLACK = "\x1b[30m";
global.RED = "\x1b[31m";
global.GREEN = "\x1b[32m";
global.YELLOW = "\x1b[33m";
global.BLUE = "\x1b[34m";
global.PURPLE = "\x1b[35m";
global.CYAN = "\x1b[36m";
global.LIGHT_GRAY = "\x1b[37m";
global.DARK_GRAY = "\x1b[90m";
global.LIGHT_RED = "\x1b[91m";
global.LIGHT_GREEN = "\x1b[92m";
global.LIGHT_YELLOW = "\x1b[93m";
global.LIGHT_BLUE = "\x1b[94m";
global.LIGHT_MAGENTA = "\x1b[95m";
global.LIGHT_CYAN = "\x1b[96m";
global.WHITE = "\x1b[97m";
global.RESET = "\x1b[0m";
